receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
  transform:
    error_mode: ignore
    log_statements:
      - context: log
        statements:
          - set(attributes["traceid"], body["request_id"])
          - set(body["trace.id"], body["request_id"])

exporters:
  # Enabled from time-to-time to view telemetry in the logs
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - debug # Lets us view spans in logs
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters:
        - debug
    logs:
      receivers: [otlp]
      processors: [batch, transform]
      exporters:
        - debug
